### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by 1-800-jono** [code-kotis/react-floating-label#6]
Not sure how to use this from the example provided.

For example how do I use it in the context of an input and where do I insert the label text?

**Comment by gokulkrishh** [comment]
Hi @jonathanphz sure. Check below example

```js
<FloatingLabel
   type="text" // All valid input types are accecpted
   placeholder="Enter the full name" // This is the label name
/>
```

Check Props section for all the available props for `FloatingLabel`. Let me know if this didn't answers your question. Thanks

**Comment by 1-800-jono** [comment]
Hey @gokulkrishh thanks very much man - appreciate it!

**Comment by gokulkrishh** [comment]
@jonathanphz Closing this issue. As its addressed in above comment.
